[package]
name = "p34_macro_example_derive"
version = "0.1.0"
authors = ["Tralinc <yecanlin2@qq.com>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "0.14.4"
quote = "0.6.3"
